--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Arisify/LanguageLib
build-by-default: true
branches:
- master
projects:
  LanguageLib:
    path: ""
    model: virion
    type: library
...
